#!/bin/bash

# Enable bash "strict mode"
set -euo pipefail
IFS=$'\n\t'

cd $ZK_NOTES
git pull --rebase

xhost + > /dev/null # for xclip clipboard support

# --rm: remove container data after executing
# -v: mount zk data files
docker run \
    --rm -it \
    -v $ZK_NOTES:/zk \
    --hostname vim-zk \
    -e DISPLAY=$DISPLAY \
    -v /tmp/.X11-unix:/tmp/.X11-unix vim-zk
xhost - > /dev/null # also for xclip

# Sync Zettelkasten data after user exited the zk system
git add .
git commit -m "Auto sync" || true
git push
cd -

# "strict mode" will stop script before this line if something goes wrong
echo Successfully synced.
